apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrt.fullname" . }}
  labels:
    {{- include "vrt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 4200
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "vrt.selectorLabels" . | nindent 4 }}
