{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaskiq.fullname" . }}
  labels:
    {{- include "chaskiq.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # DATABASE_URL: Zm9v
  # REDIS_URL: Zm9v
  # SECRET_KEY_BASE: Zm9v
  # ADMIN_PASSWORD: Zm9v
  # AWS_ACCESS_KEY_ID: your amazon access key id
  # AWS_SECRET_ACCESS_KEY: your amazon secret key id
  # SES_USERNAME: ses username
  # SES_PASSWORD: ses password
  # EOCODER_API_KEY: geocoder api key (optional)
  # SCOUT_KEY: ScoutAMP key , optional
  # BUGSNAG_API_KEY: bugsnag api key (optional)
{{- end }}
