{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "livebook.fullname" . }}
  labels:
    {{- include "livebook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  livebook_password: {{ .Values.secret.password | b64enc }}
{{- end }}
