name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.8.1
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Run chart-testing (lint)
        run: ct lint
      - name: Run chart-testing (install)
        run: ct install
